In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [15]:
df = pd.read_csv("groceries - groceries.csv")
df.shape

(9835, 33)

In [16]:
df.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.columns

Index(['Item(s)', 'Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6',
       'Item 7', 'Item 8', 'Item 9', 'Item 10', 'Item 11', 'Item 12',
       'Item 13', 'Item 14', 'Item 15', 'Item 16', 'Item 17', 'Item 18',
       'Item 19', 'Item 20', 'Item 21', 'Item 22', 'Item 23', 'Item 24',
       'Item 25', 'Item 26', 'Item 27', 'Item 28', 'Item 29', 'Item 30',
       'Item 31', 'Item 32'],
      dtype='object')

In [17]:
df.tail()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
9830,17,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,1,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,10,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,4,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,5,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# One hot encoding item
basket_sets = pd.get_dummies(df.drop(columns=['Item(s)'], axis=1), prefix="item")
basket_sets = basket_sets.groupby(level=0, axis=1).sum()
basket_sets

,item_Instant food products,item_UHT-milk,item_abrasive cleaner,item_artif. sweetener,item_baby cosmetics,item_baby food,item_bags,item_baking powder,item_bathroom cleaner,item_beef,...,item_turkey,item_vinegar,item_waffles,item_whipped/sour cream,item_whisky,item_white bread,item_white wine,item_whole milk,item_yogurt,item_zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
9831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

Association rule learning works on the concept of If and Else Statement, such as if A then B.

Aâ†’B

Ifâ†’Then

Here the If element is called antecedent, and then statement is called as Consequent. 

These types of relationships where we can find out some association or correlation between two items is known as single cardinality. 

It is all about creating rules, and if the number of items increases, then cardinality also increases accordingly.

So, to measure the associations between thousands of data items, there are several metrics. These metrics are given below:

1.Support

2.Confidence

3.Lift

In [37]:
# Filter items with support more than 3%
frequent_itemsets = apriori(basket_sets, min_support=0.03 ,use_colnames=True)
frequent_itemsets.shape

(63, 2)

In [38]:
frequent_itemsets.tail()

     support                                    itemsets
58  0.048907     (item_root vegetables, item_whole milk)
59  0.040061                (item_whole milk, item_soda)
60  0.042298      (item_whole milk, item_tropical fruit)
61  0.032232  (item_whole milk, item_whipped/sour cream)
62  0.056024              (item_yogurt, item_whole milk)

SUPPORT:--

Support is the frequency of item or how frequently an item appears in the dataset. It is defined as the fraction of the transaction T that contains the itemset X. If there are X datasets, then for transactions T, it can be written as:

SUPPORT = FREQUENCY(ITEM)/#TRANSACTIONS

CONFIDENCE:--

Confidence indicates how often the items A and B occur together in the dataset when the occurrence of A is already given. It is the ratio of the transaction that contains A and B to the number of records that contain A.

CONFIDENCE=FREQ(A,B)/FREQ(A)

LIFT:--

The lift of a rule is the ratio of the observed support to that expected if A and B were independent, and is defined as

lift(Aâ‡’B)=supp(AâˆªB)/(supp(A)supp(B))

Greater lift values indicate stronger associations.

In [39]:
# List the top100 of itemsets with strong association
rules = association_rules(frequent_itemsets, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
31,(item_whipped/sour cream),(item_whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
26,(item_root vegetables),(item_whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
6,(item_root vegetables),(item_other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
29,(item_tropical fruit),(item_whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,0.015486,1.247252
32,(item_yogurt),(item_whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132
16,(item_pip fruit),(item_whole milk),0.075648,0.255516,0.030097,0.397849,1.557043,0.010767,1.236375
11,(item_other vegetables),(item_whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,0.025394,1.214013
15,(item_pastry),(item_whole milk),0.088968,0.255516,0.033249,0.373714,1.462587,0.010516,1.188729
3,(item_citrus fruit),(item_whole milk),0.082766,0.255516,0.030503,0.368550,1.442377,0.009355,1.179008
9,(item_tropical fruit),(item_other vegetables),0.104931,0.193493,0.035892,0.342054,1.767790,0.015589,1.225796
18,(item_sausage),(item_rolls/buns),0.093950,0.183935,0.030605,0.325758,1.771048,0.013324,1.210344
12,(item_yogurt),(item_other vegetables),0.139502,0.193493,0.043416,0.311224,1.608457,0.016424,1.170929
1,(item_bottled water),(item_whole milk),0.110524,0.255516,0.034367,0.310948,1.216940,0.006126,1.080446
22,(item_rolls/buns),(item_whole milk),0.183935,0.255516,0.056634,0.307905,1.205032,0.009636,1.075696
10,(item_whole milk),(item_other vegetables),0.255516,0.193493,0.074835,0.292877,1.513634,0.025394,1.140548
24,(item_yogurt),(item_rolls/buns),0.139502,0.183935,0.034367,0.246356,1.339363,0.008708,1.082825
7,(item_other vegetables),(item_root vegetables),0.193493,0.108998,0.047382,0.244877,2.246605,0.026291,1.179941
4,(item_rolls/buns),(item_other vegetables),0.183935,0.193493,0.042603,0.231620,1.197047,0.007013,1.049620
13,(item_other vegetables),(item_yogurt),0.193493,0.139502,0.043416,0.224383,1.608457,0.016424,1.109436
23,(item_whole milk),(item_rolls/buns),0.255516,0.183935,0.056634,0.221647,1.205032,0.009636,1.048452
5,(item_other vegetables),(item_rolls/buns),0.193493,0.183935,0.042603,0.220179,1.197047,0.007013,1.046477
21,(item_soda),(item_rolls/buns),0.174377,0.183935,0.038332,0.219825,1.195124,0.006258,1.046003
33,(item_whole milk),(item_yogurt),0.255516,0.139502,0.056024,0.219260,1.571735,0.020379,1.102157
20,(item_rolls/buns),(item_soda),0.183935,0.174377,0.038332,0.208402,1.195124,0.006258,1.042983
27,(item_whole milk),(item_root vegetables),0.255516,0.108998,0.048907,0.191405,1.756031,0.021056,1.101913
25,(item_rolls/buns),(item_yogurt),0.183935,0.139502,0.034367,0.186844,1.339363,0.008708,1.058220
8,(item_other vegetables),(item_tropical fruit),0.193493,0.104931,0.035892,0.185497,1.767790,0.015589,1.098913
19,(item_rolls/buns),(item_sausage),0.183935,0.093950,0.030605,0.166390,1.771048,0.013324,1.086899
28,(item_whole milk),(item_tropical fruit),0.255516,0.104931,0.042298,0.165539,1.577595,0.015486,1.072631
0,(item_whole milk),(item_bottled water),0.255516,0.110524,0.034367,0.134501,1.216940,0.006126,1.027703
14,(item_whole milk),(item_pastry),0.255516,0.088968,0.033249,0.130123,1.462587,0.010516,1.047312
30,(item_whole milk),(item_whipped/sour cream),0.255516,0.071683,0.032232,0.126144,1.759754,0.013916,1.062323
2,(item_whole milk),(item_citrus fruit),0.255516,0.082766,0.030503,0.119379,1.442377,0.009355,1.041577
17,(item_whole milk),(item_pip fruit),0.255516,0.075648,0.030097,0.117788,1.557043,0.010767,1.047765